server:
  port:9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 456412
